### ISSUE TITLE
wooio/htmltopdf-java works on localhost and doesn't work on remote server(Public IP)

### ISSUE THREAD

**Issue by shridharsahucequity** [wooio/htmltopdf-java#15] opened 2018-11-23 08:13 UTC
Hi,

wooio/htmltopdf-java works fine for me in localhost but it is not working properly in remote server(Public IP). I am getting following error** java.nio.file.NoSuchFileException: D:\pdf\54\Report.pdf**

Thank,
Shridhar

**Comment by benbarkay** [comment] 2018-11-26 15:20
It's hard to tell without seeing a snippet of your code. If you run a Linux server then it's likely that when you told htmltopdf to write to `D:\..`, it actually wrote it to `WORKING_DIRECTORY/D\:\\...` (Linux has no concept of drive names like that).

**Comment by shridharsahucequity** [comment] 2018-11-27 05:34
I have deployed wkhtmltopdf on remote server(Windows) and its working properly. I have defined a servlet from which PDF generation logic is invoked. Below is the code for pdf generation logic.

Case 1:
When i hit the web link  from the browser of remote server(localhost:4503). PDF is generated successfully in the given path.
HtmlToPdf.create().marginLeft("0mm").marginTop("4mm").marginBottom("4mm").marginRight("0mm").disableSmartShrinking(true).object(HtmlToPdfObject.forUrl("**https://localhost:4503/pdfpage**")).convert("D:\Report.pdf");

Case 2:
When i hit the link through public IP of server(223.xxx.xx.xx:4503)  or through domain name from any machine. PDF is not getting generated
HtmlToPdf.create().marginLeft("0mm").marginTop("4mm").marginBottom("4mm").marginRight("0mm").disableSmartShrinking(true).object(HtmlToPdfObject.forUrl("**https://223.xxx.xx.xx:4503/pdfpage**")).convert("D:\Report.pdf");

**Comment by benbarkay** [comment] 2018-11-27 08:37
If you intend on running your app on a Linux machine then you will have to do away with platform-dependent paths (such as drive names which are Windows-dependent), you can use paths such as temporary folders:

```java
String applicationName = "MyApplication";
File myTempDir = new File(System.getProperty("java.io.tmpdir"), applicationName);
if (!myTempDir.exists() && !myTempDir.mkdir()) {
    throw new IllegalStateException("Could not create temporary directory");
}
File reportFile = new File(myTempDir, "Report.pdf");
HtmlToPdf.create()
    // ...
    .convert(reportFile.getAbsolutePath());
// reportFile now has the PDF bytes
```

I am closing this issue seeing as it hasn't to do with htmltopdf but rather with filepath schemes across platforms.

**Closed by benbarkay** 2018-11-27 08:37 UTC

**Comment by amidudu** [comment] 2018-11-27 12:51
> I have deployed wkhtmltopdf on remote server(Windows) and its working properly. I have defined a servlet from which PDF generation logic is invoked. Below is the code for pdf generation logic.
> 
> Case 1:
> When i hit the web link from the browser of remote server(localhost:4503). PDF is generated successfully in the given path.
> HtmlToPdf.create().marginLeft("0mm").marginTop("4mm").marginBottom("4mm").marginRight("0mm").disableSmartShrinking(true).object(HtmlToPdfObject.forUrl("**[https://localhost:4503/pdfpage**")).convert("D:\Report.pdf](https://localhost:4503/pdfpage**%22)).convert(%22D:%5CReport.pdf)");
> 
> Case 2:
> When i hit the link through public IP of server(223.xxx.xx.xx:4503) or through domain name from any machine. PDF is not getting generated
> HtmlToPdf.create().marginLeft("0mm").marginTop("4mm").marginBottom("4mm").marginRight("0mm").disableSmartShrinking(true).object(HtmlToPdfObject.forUrl("**[https://223.xxx.xx.xx:4503/pdfpage**")).convert("D:\Report.pdf](https://223.xxx.xx.xx:4503/pdfpage**%22)).convert(%22D:%5CReport.pdf)");

HTTPS using IP? maybe the issue is SSL? I would try without HTTPS or use a valid domain & SSL
